language: julia
os:
  - osx
  - linux
julia:
  - 0.7
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly
notifications:
  email: false

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      env:
        - GKSwstype=nul
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

coveralls: true

