name = "QuakeML"
uuid = "6dae4b62-8e81-11e8-042c-0346828cfc4a"
authors = ["Andy Nowacki <a.nowacki@leeds.ac.uk>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"

[compat]
julia = "1.0"
EzXML = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
